import { NextRequest, NextResponse } from "next/server"

const mockMenuItems = [
  {
    id: 1,
    name: "Fufu & Eru",
    description: "Delicious delicacy",
    price: 30.0,
    time: "30mins",
    image: "/fufu-and-eru-african-dish.jpg",
    category: "Main Dishes",
    ingredients: [
      { id: 1, name: "Cassava", emoji: "🥔" },
      { id: 2, name: "Plantain", emoji: "🍌" },
      { id: 3, name: "Pumpkin Leaves", emoji: "🌿" },
      { id: 4, name: "Palm Oil", emoji: "🫒" },
      { id: 5, name: "Garlic", emoji: "🧄" },
      { id: 6, name: "Onions", emoji: "🧅" },
    ],
    addOns: [
      { id: 1, name: "Extra Protein", price: 5.0, image: "/grilled-fish.jpg" },
      { id: 2, name: "Fried Egg", price: 2.0, image: "/fried-egg.jpg" },
      { id: 3, name: "Extra Sauce", price: 1.5, image: "/palm-sauce.jpg" },
    ],
    toppings: [
      { id: 1, name: "Extra Garlic", price: 0.5, image: "/bunch-of-garlic.png" },
      { id: 2, name: "Fresh Herbs", price: 1.0, image: "/fresh-herbs.jpg" },
      { id: 3, name: "Chili Flakes", price: 0.75, image: "/bowl-of-chili.png" },
    ],
    complements: [
      { id: 1, name: "Rice", price: 3.0, image: "/bowl-of-white-rice.png" },
      { id: 2, name: "Plantain Chips", price: 4.0, image: "/plantain-chips.png" },
    ],
  },
  {
    id: 2,
    name: "Jollof Rice",
    description: "Flavorful rice dish",
    price: 25.0,
    time: "25mins",
    image: "/vibrant-jollof-rice.png",
    category: "Main Dishes",
    ingredients: [
      { id: 1, name: "Long Grain Rice", emoji: "🍚" },
      { id: 2, name: "Tomatoes", emoji: "🍅" },
      { id: 3, name: "Peppers", emoji: "🌶️" },
      { id: 4, name: "Onions", emoji: "🧅" },
      { id: 5, name: "Carrots", emoji: "🥕" },
    ],
    addOns: [
      { id: 1, name: "Grilled Chicken", price: 8.0, image: "/grilled-chicken.png" },
      { id: 2, name: "Shrimp", price: 10.0, image: "/cooked-shrimp-platter.png" },
    ],
    toppings: [
      { id: 1, name: "Green Peas", price: 1.0, image: "/green-peas.jpg" },
      { id: 2, name: "Corn", price: 1.0, image: "/field-of-ripe-corn.png" },
    ],
    complements: [
      { id: 1, name: "Coleslaw", price: 2.5, image: "/coleslaw-salad.jpg" },
      { id: 2, name: "Fried Plantain", price: 3.5, image: "/fried-plantain.jpg" },
    ],
  },
  {
    id: 3,
    name: "Grilled Vegetables",
    description: "Fresh and healthy",
    price: 24.0,
    time: "25mins",
    image: "/grilled-vegetables.jpg",
    category: "Main Dishes",
    ingredients: [],
    addOns: [],
    toppings: [],
    complements: [],
  },
  {
    id: 4,
    name: "Fried Rice",
    description: "Savory combination",
    price: 22.0,
    time: "20mins",
    image: "/fried-rice-asian.jpg",
    category: "Main Dishes",
    ingredients: [],
    addOns: [],
    toppings: [],
    complements: [],
  },
  {
    id: 5,
    name: "Spring Rolls",
    description: "Crispy appetizer",
    price: 15.0,
    time: "15mins",
    image: "/fresh-spring-rolls.png",
    category: "Starters",
    ingredients: [],
    addOns: [],
    toppings: [],
    complements: [],
  },
  {
    id: 6,
    name: "Garlic Bread",
    description: "Warm and buttery",
    price: 12.0,
    time: "10mins",
    image: "/garlic-bread.png",
    category: "Starters",
    ingredients: [],
    addOns: [],
    toppings: [],
    complements: [],
  },
]

export async function GET(request: NextRequest) {
  return NextResponse.json(mockMenuItems)
}
