// lib/utils/icon-mapping.ts
import {
  Users,
  Utensils,
  ShoppingCart,
  Wrench,
  Shield,
  Phone,
  Bell,
  Key,
  Sprout,
  Droplets,
  Heart,
  Coffee,
  Car,
  Building,
  Bed,
  Tv,
  Wifi,
  Thermometer,
  Zap,
  Cloud,
  Star,
  Award,
  Gift,
  Package,
  Truck,
  Mail,
  MessageCircle,
  Video,
  Music,
  Camera,
  Headphones,
  Mic,
  Radio,
  Calendar,
  Clock,
  MapPin,
  Navigation,
  Globe,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Search,
  Filter,
  Settings,
  User,
} from "lucide-react";

// Simplified icon mapping with only essential icons
export const iconMapping: Record<string, any> = {
  // Service icons
  "fa-phone": Phone,
  MdOutlineSecurity: Shield,
  "fa-bell": Bell,
  "fa-key": Key,
  "fa-utensils": Utensils,
  "fa-broom": ShoppingCart,
  "fa-tools": Wrench,
  "fa-spa": Sprout,
  "fa-wine-glass": Droplets,
  "fa-heart": Heart,
  "fa-coffee": Coffee,
  "fa-car": Car,
  "fa-building": Building,
  "fa-bed": Bed,
  "fa-tv": Tv,
  "fa-wifi": Wifi,
  "fa-thermometer": Thermometer,
  "fa-bolt": Zap,
  "fa-cloud": Cloud,
  "fa-star": Star,
  "fa-award": Award,
  "fa-gift": Gift,
  "fa-package": Package,
  "fa-truck": Truck,
  "fa-envelope": Mail,
  "fa-comment": MessageCircle,
  "fa-video": Video,
  "fa-music": Music,
  "fa-camera": Camera,
  "fa-headphones": Headphones,
  "fa-microphone": Mic,
  "fa-radio": Radio,
  "fa-calendar": Calendar,
  "fa-clock": Clock,
  "fa-map-marker": MapPin,
  "fa-location-arrow": Navigation,
  "fa-globe": Globe,
  "fa-lock": Lock,
  "fa-unlock": Unlock,
  "fa-eye": Eye,
  "fa-eye-slash": EyeOff,
  "fa-search": Search,
  "fa-filter": Filter,
  "fa-cog": Settings,
  "fa-user": User,
  "fa-users": Users,

  // Common additional icons
  "fa-users": Users,
  "fa-user-plus": User,
  "fa-user-check": User,
  "fa-user-times": User,
  "fa-heart-o": Heart,
  "fa-thumbs-up": ThumbsUp,
  "fa-flag": Flag,
  "fa-exclamation-circle": AlertCircle,
  "fa-exclamation-triangle": AlertTriangle,
  "fa-check-circle": CheckCircle,
  "fa-times-circle": XCircle,
  "fa-info-circle": Info,
  "fa-question-circle": HelpCircle,
  "fa-external-link": ExternalLink,
  "fa-download": Download,
  "fa-upload": Upload,
  "fa-share": Share,
  "fa-copy": Copy,
  "fa-edit": Edit,
  "fa-trash": Trash,
  "fa-archive": Archive,
  "fa-inbox": Inbox,
  "fa-folder": Folder,
  "fa-file": File,
  "fa-file-text": FileText,
  "fa-image": Image,
  "fa-film": Film,
  "fa-book": Book,
  "fa-book-open": BookOpen,
  "fa-newspaper": Newspaper,
  "fa-compass": Compass,
  "fa-map": Map,
  "fa-shopping-bag": ShoppingBag,
  "fa-credit-card": CreditCard,
  "fa-dollar": DollarSign,
  "fa-euro": Euro,
  "fa-pound": PoundSterling,
  "fa-bitcoin": Bitcoin,

  // Fallback
  default: Users,
};

// Import remaining icons
import {
  ThumbsUp,
  Flag,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Info,
  HelpCircle,
  ExternalLink,
  Download,
  Upload,
  Share,
  Copy,
  Edit,
  Trash,
  Archive,
  Inbox,
  Folder,
  File,
  FileText,
  Image,
  Film,
  Book,
  BookOpen,
  Newspaper,
  Compass,
  Map,
  ShoppingBag,
  CreditCard,
  DollarSign,
  Euro,
  PoundSterling,
  Bitcoin,
} from "lucide-react";

export function getIconComponent(iconName: string) {
  return iconMapping[iconName] || iconMapping.default;
}
